language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t $USERNAME/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true $USERNAME/react-test npm test

after_sucess:
    - docker build -t $USERNAME/multi-client ./client
    - docker build -t $USERNAME/multi-nginx ./nginx 
    - docker build -t $USERNAME/multi-server ./server
    - docker build -t $USERNAME/multi-worker ./worker
    # login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push $USERNAME/multi-nginx
    - docker push $USERNAME/multi-client
    - docker push $USERNAME/multi-server
    - docker push $USERNAME/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-2-064877420767
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY   


# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY
