sudo: required
services:
    - docker
before_install:
    - docker build -t ted/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run ted/react-test npm run test 

after_sucess:
    - docker build -t ted/multi-client ./client
    - docker build -t ted/multi-nginx ./nginx 
    - docker build -t ted/multi-server ./server
    - docker build -t ted/multi-worker ./worker
    # login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push ted/multi-client
    - docker push ted/multi-nginx
    - docker push ted/multi-server
    - docker push ted/multi-worker



